### ISSUE TITLE
建议加上安全限制

### ISSUE THREAD

**Issue by theLastWinner** [goldfishh/chatgpt-tool-hub#10]
你好，目前工具是链接了个人订阅号，如果开启了tool，对于熟悉tool的用户来说，可能会使用这个tool来读取订阅号所在服务器的信息，甚至做一些非法操作。建议可以加上安全限制，比如使用口令，减少危险，也方便推广。谢谢。

**Comment by goldfishh** [comment]
这是wechat插件那块的issue了，等下次插件更新吧

**Comment by goldfishh** [comment]
最近精力不太够，欢迎你向chatgpt-on-wechat项目提pr
