### ISSUE TITLE
wikipedia出错

### ISSUE THREAD

**Issue by sardingking** [goldfishh/chatgpt-tool-hub#11]
bot $tool 使用工具wikipedia 查找：小红帽

[bot] the response to the original input question in chineseThought: Do I need to use a tool? Yes
Action: requests_get, "https://zh.wikipedia.org/wiki/%E5%B0%8F%E7%BA%A2%E5%B8%BD"

**Comment by goldfishh** [comment]
共性问题：https://github.com/goldfishh/chatgpt-tool-hub/issues/9#issue-1660325995
