### ISSUE TITLE
能说一下怎么在chatgpt-on-wechat项目上加google search吗

### ISSUE THREAD

**Issue by Maddaxman** [goldfishh/chatgpt-tool-hub#12]
如题，我是小白，我把chatgpt-tool-hub项目里tool文件夹里的google_search文件复制到chatgpt-on-wechat项目里插件的文件夹里，配置了googlesearch的key和id，运行后，发送google search指令会报错，正确的操作方式应该是怎么样的
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/31379908/231111198-da825106-eed5-405d-92d1-de7cec1d40f0.png">

<img width="754" alt="image" src="https://user-images.githubusercontent.com/31379908/231112975-45fba860-6579-4b03-bf49-e1fb83f5cc12.png">

**Comment by goldfishh** [comment]
不用复制吖，我推荐用bing搜索

**Comment by Maddaxman** [comment]
> 不用复制吖，我推荐用bing搜索

我试试

**Comment by Maddaxman** [comment]
> 不用复制吖，我推荐用bing搜索

@goldfishh  chatgpt-on-wechat包里的plugins文件夹没有bing的文件夹，咋搞，复制tool项目包里的bing文件夹到plugins文件夹里吗？

**Comment by Maddaxman** [comment]
> > 不用复制吖，我推荐用bing搜索
> 
> 我试试
@goldfishh  bing绑卡不好搞，试了一下绑depay卡失败了，能教一下搞google的吗

**Comment by xionghaizhi** [comment]
![image](https://user-images.githubusercontent.com/30396478/232200602-9f7c2d5f-2488-4d75-a97f-5fe4c7235f98.png)
我的chat能访问，代理也加了，google这个还是超时呢？

**Comment by xionghaizhi** [comment]
@goldfishh 
![image](https://user-images.githubusercontent.com/30396478/232200672-d24fccd3-15f5-46f7-b36a-32453d52b9a3.png)
代理配置了，chat也可以使用，但是谷歌超时！

**Comment by forczc** [comment]
> @goldfishh ![image](https://user-images.githubusercontent.com/30396478/232200672-d24fccd3-15f5-46f7-b36a-32453d52b9a3.png) 代理配置了，chat也可以使用，但是谷歌超时！

要加代理，得自己改代码

**Comment by xionghaizhi** [comment]
> > @goldfishh ![image](https://user-images.githubusercontent.com/30396478/232200672-d24fccd3-15f5-46f7-b36a-32453d52b9a3.png) 代理配置了，chat也可以使用，但是谷歌超时！
> 
> 要加代理，得自己改代码

可以告诉我改哪个文件吗？

**Comment by xionghaizhi** [comment]
> > > > @goldfishh ![image](https://user-images.githubusercontent.com/30396478/232200672-d24fccd3-15f5-46f7-b36a-32453d52b9a3.png) 代理配置了，chat也可以使用，但是谷歌超时！
> > > 
> > > 
> > > 要加代理，得自己改代码
> > 
> > 
> > 可以告诉我改哪个文件吗？
> 
> 1. chatgpt_tool_hub/tools/google_search/wrapper.py 文件
>    `def _google_search_results(self, search_term: str, **kwargs: Any) -> List[dict]: //***加代码start*** if self.proxy: proxies = {'http': self.proxy, 'https': self.proxy} else: proxies = None //***加代码end*** res = ( self.search_engine.cse() .list(q=search_term, cx=self.google_cse_id, **kwargs) //***改代码start*** .execute(proxies=proxies) //***改代码end*** ) return res.get("items", [])`
> 2. chatgpt_tool_hub/tools/google_search/tool.py 文件
>    最后一行，在"google_cse_id"参数后面，加一个"common_proxy"参数（你喜欢改其它名也行）
> 3. 在你配置google_cse_id的地方，也配置多一个"common_proxy"参数，值就是你的代理地址，比如"http://127.0.0.1:7890"

谢谢 ！
