### ISSUE TITLE
早报请求超时的问题

### ISSUE THREAD

**Issue by Li-Eternally** [goldfishh/chatgpt-tool-hub#16]
chatgpt-on-wechat版本：1.2.3
chatgpt-tool-hub版本：0.3.9

从昨天开始早报就一直请求超时，看了下接口调用日志是有返回内容的，是我哪里配置的不对吗？

------------------------------------------------------------------------------------------
[INFO][2023-04-13 15:03:29][bridge.py:28] - create bot chatGPT for chat
[INFO][2023-04-13 15:03:56][base.py:109] - 执行Tool: morning-news中...
[INFO][2023-04-13 15:03:56][bot.py:87] - 行动输入: 给我今天的早报
[WARNING][2023-04-13 15:04:57][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=60).
[ERROR][2023-04-13 15:06:01][victorinox.py:86] - [APP] catch a Exception: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=60)
[INFO][2023-04-13 15:06:36][base.py:109] - 执行Tool: morning-news中...
[INFO][2023-04-13 15:06:36][bot.py:87] - 行动输入: 给我今天的早报
[WARNING][2023-04-13 15:07:36][before_sleep.py:65] - Retrying chatgpt_tool_hub.models.chatgpt.chatgpt.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=60).
[ERROR][2023-04-13 15:08:41][victorinox.py:86] - [APP] catch a Exception: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=60)
[ERROR][2023-04-13 15:08:41][victorinox.py:90] - exceed retry_num
[ERROR][2023-04-13 15:08:41][tool.py:92] - 超过重试次数
------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/128838111/231805814-c3fa0da3-76e0-45ce-8bb1-dc51e12d7536.png)

我是试着修改下面的配置，但还是没用
  "request_timeout": 300,
  "timeout": 300,

**Comment by Li-Eternally** [comment]
> 这里有一个bug，你可以先用REQUEST_TIMEOUT环境变量规避一下，我应该这周末更新它

ok，已解决，目前能正常使用

**Comment by LINKlang** [comment]
> 这里有个bug，你可以先用REQUEST_TIMEOUT环境变量规避一下，我应该这周末更新它

@goldfishh 请问怎么改呢，求指导

**Comment by xionghaizhi** [comment]
> > 这里有一个bug，你可以先用REQUEST_TIMEOUT环境变量规避一下，我应该这周末更新它
> 
> ok，已解决，目前能正常使用 顺便提出一个建议，在早报的最后有一个图片链接，就是说能不能发送这张图片而不是发送文字信息，我觉得直接发送图片会不会更快些 ![屏幕截图 2023-04-15 123219](https://user-images.githubusercontent.com/128838111/232183178-20bcc3cf-14eb-434d-a6bc-a0dfcfbdb0fd.png) ![屏幕截图 2023-04-15 123232](https://user-images.githubusercontent.com/128838111/232183181-3fc5e135-6c32-4930-b493-75efb1636240.png)

怎么改的？
![image](https://user-images.githubusercontent.com/30396478/232201094-1d4b318f-6c44-4ad4-8aa8-4fbc39336668.png)
我这样对吗？

**Comment by Li-Eternally** [comment]
@xionghaizhi @LINKlang 
进入以下目录
/usr/local/lib/python3.xx/dist-packages/chatgpt_tool_hub/models/
打开  __init__.py  文件
![image](https://user-images.githubusercontent.com/128838111/232202560-86090dd8-7393-4f77-ba26-8bfb34cdf275.png)
将  "REQUEST_TIMEOUT", 60  改为80往上，建议不要太高根据实际情况而定。
目前暂时的解决办法可解决部分插件超时的问题，后续请耐心等待作者更新。

**Comment by xionghaizhi** [comment]
> @xionghaizhi @LINKlang 进入以下目录 /usr/local/lib/python3.xx/dist-packages/chatgpt_tool_hub/models/ 打开 **init**.py 文件 ![image](https://user-images.githubusercontent.com/128838111/232202560-86090dd8-7393-4f77-ba26-8bfb34cdf275.png) 将 "REQUEST_TIMEOUT", 60 改为80往上，建议不要太高根据实际情况而定。 目前暂时的解决办法可解决部分插件超时的问题，后续请耐心等待作者更新。

谢谢
