### ISSUE TITLE
wechat项目上使用wolfram-alpha插件出错

### ISSUE THREAD

**Issue by Maddaxman** [goldfishh/chatgpt-tool-hub#17]
已在config.json配置了appid 以及把wolfram-alpha包复制到到WeChat项目里

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/31379908/232094548-af4d88f5-83e6-47d3-9ef6-0beb48744da8.png">

**Comment by goldfishh** [comment]
这个像是你本地库的问题，去google找找相似问题？
