### ISSUE TITLE
tool 插件运行 初始化失败

### ISSUE THREAD

**Issue by zhenghan12138** [goldfishh/chatgpt-tool-hub#23]
sample-chatgpt-on-wechat  | chatgpt-tool-hub version: 0.3.14
sample-chatgpt-on-wechat  | chatgpt-tool-hub 0.3.8后，部分工具名将变更：requests -> url-get
sample-chatgpt-on-wechat  | [ERROR][2023-04-18 09:04:09][plugin_manager.py:110] - Failed to import plugin tool: No module named 'webdriver_manager'
sample-chatgpt-on-wechat  | Traceback (most recent call last):
sample-chatgpt-on-wechat  |   File "/app/plugins/plugin_manager.py", line 105, in scan_plugins
sample-chatgpt-on-wechat  |     self.loaded[plugin_path] = importlib.import_module(
sample-chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
sample-chatgpt-on-wechat  |     return _bootstrap._gcd_import(name[level:], package, level)
sample-chatgpt-on-wechat  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
sample-chatgpt-on-wechat  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
sample-chatgpt-on-wechat  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
sample-chatgpt-on-wechat  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
sample-chatgpt-on-wechat  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
sample-chatgpt-on-wechat  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
sample-chatgpt-on-wechat  |   File "/app/plugins/tool/__init__.py", line 1, in <module>
sample-chatgpt-on-wechat  |     from .tool import *
sample-chatgpt-on-wechat  |   File "/app/plugins/tool/tool.py", line 4, in <module>
sample-chatgpt-on-wechat  |     from chatgpt_tool_hub.apps import load_app
sample-chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/apps/__init__.py", line 1, in <module>
sample-chatgpt-on-wechat  |     from chatgpt_tool_hub.apps.load_app import load_app
sample-chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/apps/load_app.py", line 7, in <module>
sample-chatgpt-on-wechat  |     from chatgpt_tool_hub.tools import dynamic_tool_loader
sample-chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/__init__.py", line 5, in <module>
sample-chatgpt-on-wechat  |     from chatgpt_tool_hub.tools.web_requests.browser import BrowserTool
sample-chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/web_requests/__init__.py", line 42, in <module>
sample-chatgpt-on-wechat  |     from chatgpt_tool_hub.tools.web_requests.wrapper import RequestsWrapper
sample-chatgpt-on-wechat  |   File "/usr/local/lib/python3.10/site-packages/chatgpt_tool_hub/tools/web_requests/wrapper.py", line 11, in <module>
sample-chatgpt-on-wechat  |     from webdriver_manager.chrome import ChromeDriverManager
sample-chatgpt-on-wechat  | ModuleNotFoundError: No module named 'webdriver_manager'

**Comment by doublet444** [comment]
sample-chatgpt-on-wechat | ModuleNotFoundError: No module named 'webdriver_manager'   PIP  install 一下

**Comment by goldfishh** [comment]
请使用最新发布的0.4.1 版本

**Comment by goldfishh** [comment]
0.3版本管理不到位导致的问题，新版本不会再出现了，如仍有问题，请重新开启issue
