### ISSUE TITLE
[morning-news] init failed, error_info: ValueError('Did not find zaobao_api_key, please add an environment variable `ZAOBAO_API_KEY` which contains it, or pass  `zaobao_api_key` as a named parameter.')

### ISSUE THREAD

**Issue by LumingMelody** [goldfishh/chatgpt-tool-hub#26]
### 问题描述

0. 你的问题是否在test.py能复现？

1. 你复现时的config.json，**注意抹去你的api-key**
```json
{
  "tools": [],
  "kwargs": {
      "debug": true  // debug模式一定要打开
  }
}
```

2. 你的问题：
log里面老是读不到可以 是要在哪里配置 
```text
[morning-news] init failed, error_info: ValueError('Did not find zaobao_api_key, please add an environment variable `ZAOBAO_API_KEY` which contains it, or pass  `zaobao_api_key` as a named parameter.')
[news-api] init failed, error_info: ValueError('Did not find news_api_key, please add an environment variable `NEWS_API_KEY` which contains it, or pass  `news_api_key` as a named parameter.')
```

3. 收到ai的回复：

```text
[替换我]
```

4. debug模式终端打印的日志：

```text
[替换我]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python -V` )：                      
 - pip版本  ( 执行 `pip -V`)：

**Comment by goldfishh** [comment]
news 目前是默认工具，他作为父tool包含三个子news tool，子tool会根据你的api-key来决定是否注册，这些日志实际不影响你的使用

**Comment by LumingMelody** [comment]
> news 目前是默认工具，他作为父tool包含三个子news tool，子tool会根据你的api-key来决定是否注册，这些日志实际不影响你的使用

那我的config.json应该放在那个根目录呢

**Comment by LumingMelody** [comment]
> news 目前是默认工具，他作为父tool包含三个子news tool，子tool会根据你的api-key来决定是否注册，这些日志实际不影响你的使用

<property object at 0x7f9c89bdcc20>: APIConnectionError(message='Error communicating with OpenAI', http_status=None, request_id=None)
还有这个

**Comment by goldfishh** [comment]
> > news 目前是默认工具，他作为父tool包含三个子news tool，子tool会根据你的api-key来决定是否注册，这些日志实际不影响你的使用
> 
> 那我的config.json应该放在那个根目录呢

如果你用的是chatgp-on-wechat tool插件，那么你需要存放在plugins/tool下，和tool.py同路径

property object 这个字样，我在fix

**Comment by LumingMelody** [comment]
还有一个问题就是使用Google-search的时候 返回的不是结果 而是这个 [蔍鸣霸霸] 我使用了url-get工具，输入了"https://www.google.com/search?q=Python"，并得到了关于Python的搜索结果页面。

**Comment by goldfishh** [comment]
注意：早报在最新版更改：zaobao_api_key -> morning_news_api_key
