### ISSUE TITLE
关于News新闻和天气的两个小问题

### ISSUE THREAD

**Issue by Li-Eternally** [goldfishh/chatgpt-tool-hub#27]
##### 4. 在已有 issue 中未搜索到类似问题
chatgpt-on-wechat：1.2.3.2
chatgpt-tool-hub：0.4.1

### 问题描述
AI在发送新闻内容的前面会带上一串字符，在获取天气的时候AI回复的是英文

![image](https://user-images.githubusercontent.com/128838111/233152007-333956ec-b896-4a28-96c9-3ee1823488cc.png)
![image](https://user-images.githubusercontent.com/128838111/233152037-d3e3b95d-153c-4a53-9333-3263b9f61409.png)

{
  "tools": [
    "news",
    "url-get",
    "terminal",
    "wikipedia",
    "bing-search",
    "meteo-weather",
    "wolfram-alpha"

  ],
  "kwargs": {
    "top_k_results": 2,
    "no_default": true,
    "debug": true,
    "searx_host": "",
    "model_name": "gpt-3.5-turbo",
    "bing_subscription_key": "81484fb4",
    "news_api_key":"89eff01a",
    "wolfram_alpha_appid":"Q93",
    "google_api_key": "AIzaS",
    "google_cse_id": "2300",
    "zaobao_api_key": "0iLA5"
  }
}

### 环境

 - 操作系统类型  ：Ubuntu-22.04-x64
 - Python版本 ：3.10                      
 - pip版本  ( 执行 `pip -V`)：

**Comment by goldfishh** [comment]
我之后会解决这两个问题

**Comment by Li-Eternally** [comment]
> 我之后会解决这两个问题

反馈：已拉取最新代码，新闻前面的乱码没有了，但是是不是少了点什么😂
![image](https://user-images.githubusercontent.com/128838111/233454576-f4bc4c2d-cd16-41e4-bdc4-7bf4d0758088.png)
![image](https://user-images.githubusercontent.com/128838111/233454608-1661fa20-b8f6-4bed-94f4-43e67e103da8.png)
另外关于meteo-weather天气的API是不是有些问题
![image](https://user-images.githubusercontent.com/128838111/233454786-d25ae98f-3cd4-4439-b2f0-bd28515c7ca0.png)
![image](https://user-images.githubusercontent.com/128838111/233454820-6d684359-5c93-42dd-9ba9-9601c7ac1256.png)

**Comment by goldfishh** [comment]
> > 我之后会解决这两个问题
> 
> 反馈：已拉取最新代码，新闻前面的乱码没有了，但是是不是少了点什么😂 ![image](https://user-images.githubusercontent.com/128838111/233454576-f4bc4c2d-cd16-41e4-bdc4-7bf4d0758088.png) ![image](https://user-images.githubusercontent.com/128838111/233454608-1661fa20-b8f6-4bed-94f4-43e67e103da8.png) 另外关于meteo-weather天气的API是不是有些问题 ![image](https://user-images.githubusercontent.com/128838111/233454786-d25ae98f-3cd4-4439-b2f0-bd28515c7ca0.png) ![image](https://user-images.githubusercontent.com/128838111/233454820-6d684359-5c93-42dd-9ba9-9601c7ac1256.png)

我文档没及时更新所以让你有误解，现在三个news tool 合并成一个tool 了，只要配置news就会检索kwargs的api-key注册相应subtool

至于meteo的问题，看到你的日志显示你是 free trial user，有3tpm限制，使用一次meteo会调用4次openai接口因此你最少要等待1分20秒才能接收一条信息
如果你短时间内发送多条信息，wechat channel那边处理可能会造成请求争抢导致你无法获得结果，请注意调用4次接口需要保证4次均不被限速才能正常返回否则会重试

你的请求 -> 1  -> 2 -> 3 -> 4 -> 给你的回复
如果你中间被限速了，那么你的流程会重新回到1

因为考虑到pay as go用户偶尔出现网络问题报错后能迅速重试，我把重试时间改成15秒

**Comment by Li-Eternally** [comment]
> > > 我之后会解决这两个问题
> > 
> > 
> > 反馈：已拉取最新代码，新闻前面的乱码没有了，但是是不是少了点什么😂 ![image](https://user-images.githubusercontent.com/128838111/233454576-f4bc4c2d-cd16-41e4-bdc4-7bf4d0758088.png) ![image](https://user-images.githubusercontent.com/128838111/233454608-1661fa20-b8f6-4bed-94f4-43e67e103da8.png) 另外关于meteo-weather天气的API是不是有些问题 ![image](https://user-images.githubusercontent.com/128838111/233454786-d25ae98f-3cd4-4439-b2f0-bd28515c7ca0.png) ![image](https://user-images.githubusercontent.com/128838111/233454820-6d684359-5c93-42dd-9ba9-9601c7ac1256.png)
> 
> 我文档没及时更新所以让你有误解，现在三个news tool 合并成一个tool 了，只要配置news就会检索kwargs的api-key注册相应subtool
> 
> 至于meteo的问题，看到你的日志显示你是 free trial user，有3tpm限制，使用一次meteo会调用4次openai接口因此你最少要等待1分20秒才能接收一条信息 如果你短时间内发送多条信息，wechat channel那边处理可能会造成请求争抢导致你无法获得结果，请注意调用4次接口需要保证4次均不被限速才能正常返回否则会重试
> 
> 你的请求 -> 1 -> 2 -> 3 -> 4 -> 给你的回复 如果你中间被限速了，那么你的流程会重新回到1
> 
> 因为考虑到pay as go用户偶尔出现网络问题报错后能迅速重试，我把重试时间改成15秒

Ok，明白了
