### ISSUE TITLE
升级了tool-hub0.4.1 还是没能启动tool，请问这个该怎么解决？

### ISSUE THREAD

**Issue by fattank** [goldfishh/chatgpt-tool-hub#28]
### 问题描述

0. 你的问题是否在test.py能复现？

1. 你复现时的config.json，**注意抹去你的api-key**
{
  "tools": ["python", "url-get", "terminal", "meteo-weather","wolfram-alpha"],
  "kwargs": {
      "top_k_results": 2,
      "openai_api_key": "1234",
      "proxy": "",
      "debug": true,
      "no_default": false,
      "model_name": "gpt-3.5-turbo",
      "wolfram_alpha_appid": "1234"
  }
}    
```

2. 你的问题：

```text
[升级了0.4.1的tool-hub，输入 bot$tool,报错，未知插件命令，输入bot # help tool，插件不存在活未启用，输入bot # help python，插件不存在活未启用]，我主要是想启动wolfram。请问这个该怎么解决？
```

3. 收到ai的回复：

```text
[替换我]
```

4. debug模式终端打印的日志：

```text
[替换我]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python -V` )：                      
 - pip版本  ( 执行 `pip -V`)：

**Comment by fattank** [comment]
追加提问：
在log里面的情况是tool插件报错，找不到，这是日志：
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
[INFO][2023-04-20 17:32:22][plugin_manager.py:47] - Loading plugins config...
[INFO][2023-04-20 17:32:22][plugin_manager.py:63] - Scaning plugins ...
chatgpt-tool-hub version: 0.4.1
[ERROR][2023-04-20 17:32:23][plugin_manager.py:88] - Failed to import plugin tool: cannot import name 'load_app' from 'chatgpt_tool_hub.apps' (/home/tank/.local/lib/python3.8/site-packages/chatgpt_tool_hub/apps/__init__.py)
Traceback (most recent call last):
  File "/home/tank/Downloads/chatgpt-on-wechat-master0405/plugins/plugin_manager.py", line 85, in scan_plugins
    self.loaded[plugin_path] = importlib.import_module(import_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tank/Downloads/chatgpt-on-wechat-master0405/plugins/tool/__init__.py", line 1, in <module>
    from .tool import *
  File "/home/tank/Downloads/chatgpt-on-wechat-master0405/plugins/tool/tool.py", line 4, in <module>
    from chatgpt_tool_hub.apps import load_app
ImportError: cannot import name 'load_app' from 'chatgpt_tool_hub.apps' (/home/tank/.local/lib/python3.8/site-packages/chatgpt_tool_hub/apps/__init__.py)
[INFO][2023-04-20 17:32:23][plugin_manager.py:39] - Plugin Dungeon_v1.0 registered, path=./plugins/dungeon
[INFO][2023-04-20 17:32:23][plugin_manager.py:39] - Plugin Role_v1.0 registered, path=./plugins/role
[INFO][2023-04-20 17:32:23][plugin_manager.py:39] - Plugin Banwords_v1.0 registered, path=./plugins/banwords
[INFO][2023-04-20 17:32:23][plugin_manager.py:39] - Plugin Godcmd_v1.0 registered, path=./plugins/godcmd
[INFO][2023-04-20 17:32:23][plugin_manager.py:39] - Plugin BDunit_v0.1 registered, path=./plugins/bdunit
[INFO][2023-04-20 17:32:23][plugin_manager.py:39] - Plugin Hello_v0.1 registered, path=./plugins/hello
[INFO][2023-04-20 17:32:23][plugin_manager.py:39] - Plugin Finish_v1.0 registered, path=./plugins/finish
[ERROR][2023-04-20 17:32:23][plugin_manager.py:150] - Plugin tool not found, but found in plugins.json
[INFO][2023-04-20 17:32:23][godcmd.py:170] - [Godcmd] ���������������������������������������������5287���
[INFO][2023-04-20 17:32:23][godcmd.py:185] - [Godcmd] inited
[INFO][2023-04-20 17:32:23][role.py:60] - [Role] inited
[INFO][2023-04-20 17:32:23][dungeon.py:43] - [Dungeon] inited
[INFO][2023-04-20 17:32:23][hello.py:16] - [Hello] inited
[INFO][2023-04-20 17:32:23][finish.py:16] - [Finish] inited
Getting uuid of QR code.

**Comment by goldfishh** [comment]
> load_app

你好，请pull chatgpt-on-wechat最新代码，如下报错均为未更新tool 0.4插件导致
```text
[ERROR][2023-04-20 17:32:23][plugin_manager.py:88] - Failed to import plugin tool: cannot import name 'load_app' from 'chatgpt_tool_hub.apps'
```

**Comment by cyinan** [comment]
你好，我pip3 install -r requirements.txt，pip3 install -r requirements-optional.txt这两个依赖都更新了，项目也用git pull更新了，都正常，但是启动后$tool，就是不能用，提示，[ERROR]
未知插件命令
查看插件命令列表请输入#help 插件名，之前默认的4个还可以用，现在全部不能用了，这是啥原因？

**Comment by fattank** [comment]
多谢，已经更新代码，已经搞定，就是wolfram有点不稳定。非常感谢。
> > load_app
> 
> 
> 
> 你好，请pull chatgpt-on-wechat最新代码，如下报错均为未更新tool 0.4插件导致
> 
> ```text
> 
> [ERROR][2023-04-20 17:32:23][plugin_manager.py:88] - Failed to import plugin tool: cannot import name 'load_app' from 'chatgpt_tool_hub.apps'
> 
> ```
