### ISSUE TITLE
项目依赖均已更新至最新，tool工具用不起来，提示未知插件命令！

### ISSUE THREAD

**Issue by cyinan** [goldfishh/chatgpt-tool-hub#29]
### 问题描述

0. 你的问题是否在test.py能复现？

1. 你复现时的config.json，**注意抹去你的api-key**
```json
{
  "tools": [
    "python",
    "url-get",
    "terminal",
    "meteo-weather",
    "requests",
    "morning-news",
    "wikipedia",
    "bing-search",
    "wolfram-alpha"
  ],
  "kwargs": {
    "top_k_results": 2,
    "no_default": false,
    "model_name": "gpt-3.5-turbo",
    "zaobao_api_key": "1234"
  }
}

2. 你的问题：

我pip3 install -r requirements.txt，pip3 install -r requirements-optional.txt这两个依赖都更新了，项目也用git pull更新了，都正常，但是启动后$tool，就是不能用。我输入$tool,
查看日志：
[INFO][2023-04-23 03:39:11][wechat_channel.py:196] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
未知插件命令
查看插件命令列表请输入#help 插件名
), receiver=@9905db42e440cdcd2aacd2df992549f1

3. 收到ai的回复：
[ERROR]
未知插件命令
查看插件命令列表请输入#help 插件名.]。
之前默认的4个还可以用，现在全部不能用了，这是啥原因？

4. debug模式终端打印的日志：

```text
[替换我]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python -V` )：                      
 - pip版本  ( 执行 `pip -V`)：

**Comment by zhanggw108** [comment]
我也是这个问题，在plugins.json中看到tool的状态是false

**Comment by goldfishh** [comment]
> 我也是这个问题，在plugins.json中看到tool的状态是false

你们需要反馈一下日志，大概率是最近tool插件更新后代码没有同步

需要同时同步chatgpt-on-wechat 和 tool-hub

**Comment by cyinan** [comment]
> > 我也是这个问题，在plugins.json中看到tool的状态是false
> 
> 你们需要反馈一下日志，大概率是最近tool插件更新后代码没有同步
> 
> 需要同时同步chatgpt-on-wechat 和 tool-hub

同时同步？？？，用什么命令，我上面那些命令对吗，直接git pull就行了吗，已经最新了，至于那个日志，我除了聊天那个日志，其他我不知道怎么看，算是小白，一步一步按教程来的

**Comment by goldfishh** [comment]
> > > 我也是这个问题，在plugins.json中看到tool的状态是false
> > 
> > 
> > 你们需要反馈一下日志，大概率是最近tool插件更新后代码没有同步
> > 需要同时同步chatgpt-on-wechat 和 tool-hub
> 
> 同时同步？？？，用什么命令，我上面那些命令对吗，直接git pull就行了吗，已经最新了，至于那个日志，我除了聊天那个日志，其他我不知道怎么看，算是小白，一步一步按教程来的

你好，你可能没仔细看日志，在你启动app.py时日志会有提示某个插件加载的记录
如果日志没有，你可以设置debug参数增多日志打印范围

chatgpt-on-wechat 和 tool插件目录下的config.json 都加上 debug = True的参数
这两个config.json组织虽然不一样，但你应该知道怎么添加对应的参数，tool要加到kwargs里

不出意外你能在日志找到为什么tool插件加载失败的原因，如果你无法解决再回复我具体日志

**Comment by zhanggw108** [comment]
chatgpt-tool-hub version: 0.4.1
[INFO][2023-04-24 09:20:57][plugin_manager.py:47] - Plugin tool_v0.4 registered, path=./plugins/tool
[INFO][2023-04-24 09:20:57][plugin_manager.py:47] - Plugin Role_v1.0 registered, path=./plugins/role
[DEBUG][2023-04-24 09:20:57][plugin_manager.py:178] - plugins.json config={'plugins': SortedDict({'Godcmd': {'enabled': True, 'priority': 999}, 'Keyword': {'enabled': True, 'priority': 900}, 'Banwords': {'enabled': False, 'priority': 100}, 'tool': {'enabled': False, 'priority': 1}, 'Role': {'enabled': True, 'priority': 0}, 'Dungeon': {'enabled': True, 'priority': 0}, 'BDunit': {'enabled': False, 'priority': 0}, 'Hello': {'enabled': True, 'priority': -1}, 'Finish': {'enabled': True, 'priority': -999}}, sort_func=<lambda>, reverse=True)}
启动的日志里面并没有报错，但是没有识别到tool插件。tool插件里面run.log是空的

**Comment by goldfishh** [comment]
> chatgpt-tool-hub version: 0.4.1 [INFO][2023-04-24 09:20:57][plugin_manager.py:47] - Plugin tool_v0.4 registered, path=./plugins/tool [INFO][2023-04-24 09:20:57][plugin_manager.py:47] - Plugin Role_v1.0 registered, path=./plugins/role [DEBUG][2023-04-24 09:20:57][plugin_manager.py:178] - plugins.json config={'plugins': SortedDict({'Godcmd': {'enabled': True, 'priority': 999}, 'Keyword': {'enabled': True, 'priority': 900}, 'Banwords': {'enabled': False, 'priority': 100}, 'tool': {'enabled': False, 'priority': 1}, 'Role': {'enabled': True, 'priority': 0}, 'Dungeon': {'enabled': True, 'priority': 0}, 'BDunit': {'enabled': False, 'priority': 0}, 'Hello': {'enabled': True, 'priority': -1}, 'Finish': {'enabled': True, 'priority': -999}}, sort_func=, reverse=True)} 启动的日志里面并没有报错，但是没有识别到tool插件。tool插件里面run.log是空的

可以详细说一下你是怎么部署的吗?你把plugins.json tool字典里的enabled手动设置成true然后重启了没有？

**Comment by zhanggw108** [comment]
> > chatgpt-tool-hub version: 0.4.1 [INFO][2023-04-24 09:20:57][plugin_manager.py:47] - Plugin tool_v0.4 registered, path=./plugins/tool [INFO][2023-04-24 09:20:57][plugin_manager.py:47] - Plugin Role_v1.0 registered, path=./plugins/role [DEBUG][2023-04-24 09:20:57][plugin_manager.py:178] - plugins.json config={'plugins': SortedDict({'Godcmd': {'enabled': True, 'priority': 999}, 'Keyword': {'enabled': True, 'priority': 900}, 'Banwords': {'enabled': False, 'priority': 100}, 'tool': {'enabled': False, 'priority': 1}, 'Role': {'enabled': True, 'priority': 0}, 'Dungeon': {'enabled': True, 'priority': 0}, 'BDunit': {'enabled': False, 'priority': 0}, 'Hello': {'enabled': True, 'priority': -1}, 'Finish': {'enabled': True, 'priority': -999}}, sort_func=, reverse=True)} 启动的日志里面并没有报错，但是没有识别到tool插件。tool插件里面run.log是空的
> 
> 可以详细说一下你是怎么部署的吗?你把plugins.json tool字典里的enabled手动设置成true然后重启了没有？

手动设置成true重启以后还是变成false。python版本3.8，代码clone到Linux服务器上，pip install -r requirements.txt pip3 install -r requirement-optional.txt 。配置文件都没问题

**Comment by MinovskyRickland** [comment]
auth加密码打开管理员模式 输入#enablep tool 如果打开失败吧plugin文件夹下面tool里面的config.json先删了

**Comment by mikeyang01** [comment]
> 我也是这个问题，在plugins.json中看到tool的状态是false

I deleted plugins.json, $tool works again

**Comment by goldfishh** [comment]
手动关闭长期不活跃issue，如有需求请重新打开。
