### ISSUE TITLE
morningnews和wolfram-alpha插件添加报错

### ISSUE THREAD

**Issue by Maddaxman** [goldfishh/chatgpt-tool-hub#32]
### 问题描述

0. 你的问题是否在test.py能复现？

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/31379908/233931163-639c5646-f695-4fc8-8697-ee175a2e2a6d.png">

还有morningnews也是添加不了的

**Comment by goldfishh** [comment]
感谢反馈，已fix，请关注之后commit
