### ISSUE TITLE
tool调用设置问题

### ISSUE THREAD

**Issue by nagaki09** [goldfishh/chatgpt-tool-hub#4]
![image](https://user-images.githubusercontent.com/31009189/230310489-0873e810-9cc9-45dd-a147-e42873024f74.png)
这段代码是加在 tool/config.json文档中么？

**Comment by hbsszh** [comment]
> > ![image](https://user-images.githubusercontent.com/31009189/230310489-0873e810-9cc9-45dd-a147-e42873024f74.png) 这段代码是加在 tool/config.json文档中么？
> 
> 你好，如果你需要在chatgpt-on-wechat额外使用bing-search 需要先进入申请URL获取到api-key（申请方法可参考教程）, 然后在tool/config.json的kwargs增加一个键值对： bing_subscription_key: 你申请到的api-key
> 
> 这是一个例子：
> 
> ```json
> {
>   "tools": ["bing-search"],
>   "kwargs": {
>       "no_default": false,
>       "bing_subscription_key": "YOUR_BING_SEARCH_API_KEY"
>   }
> }
> ```

您好，已按此增加相关键值。如何在微信中使用bing-search呢？

**Comment by nagaki09** [comment]
> ```json
> "bing_subscription_key": "YOUR_BING_SEARCH_API_KEY"
> ```

感谢，我试试如何触发

**Comment by nagaki09** [comment]
您好，
按照你之前的教程，申请了bing的key和wolfram的appid
并且添加在了config.json中
我在chatgpt-on-wechat 这个项目中调用时，只要加上$tool就会报错
得到的返回是：
[errror]
未知插件命令
查看插件命令列表请输入#help插件名

另外我在调用wolfram时，算1234*4321，gpt说自己已经调用了
但是给出的计算结果是：5,328,814
计算器算出来应该是：5,332,114

**Comment by goldfishh** [comment]
> 您好， 按照你之前的教程，申请了bing的key和wolfram的appid 并且添加在了config.json中 我在chatgpt-on-wechat 这个项目中调用时，只要加上$tool就会报错 得到的返回是： [errror] 未知插件命令 查看插件命令列表请输入#help插件名
> 
> 另外我在调用wolfram时，算1234*4321，gpt说自己已经调用了 但是给出的计算结果是：5,328,814 计算器算出来应该是：5,332,114

你好，我不清楚你的环境，出现这种报错原因可能是依赖没有安装好，没有使用工具，chatgpt在编造信息
你可以通过pip list | grep chatgpt-tool-hub查询chatgpt-tool-hub是否有记录

在chatgpt-on-wechat目录 pip install -r requirements-optional.txt, 重启试一试

tool插件正确安装的标志是：[触发条件] $tool       返回内容是固定的本工具帮助信息

**Comment by nagaki09** [comment]
> > 您好， 按照你之前的教程，申请了bing的key和wolfram的appid 并且添加在了config.json中 我在chatgpt-on-wechat 这个项目中调用时，只要加上$tool就会报错 得到的返回是： [errror] 未知插件命令 查看插件命令列表请输入#help插件名
> > 另外我在调用wolfram时，算1234*4321，gpt说自己已经调用了 但是给出的计算结果是：5,328,814 计算器算出来应该是：5,332,114
> 
> 你好，我不清楚你的环境，出现这种报错原因可能是依赖没有安装好，没有使用工具，chatgpt在编造信息 你可以通过pip list | grep chatgpt-tool-hub查询chatgpt-tool-hub是否有记录
> 
> 在chatgpt-on-wechat目录 pip install -r requirements-optional.txt, 重启试一试
> 
> tool插件正确安装的标志是：[触发条件] $tool 返回内容是固定的本工具帮助信息

装了optional requirements 之后 $tool有正确响应了

**Comment by nagaki09** [comment]
![9dde1008067a0f1a32a8bfd1119b319](https://user-images.githubusercontent.com/31009189/230566034-b3369b1f-7581-49fd-be03-13b251ff16a2.jpg)
还是算不对，不知道是不是我调用的方式有问题
单独用$tool指令 和bot对话时，bot会回答自己具备计算、搜索方面的能力了

**Comment by goldfishh** [comment]
> ![9dde1008067a0f1a32a8bfd1119b319](https://user-images.githubusercontent.com/31009189/230566034-b3369b1f-7581-49fd-be03-13b251ff16a2.jpg)
> 还是算不对，不知道是不是我调用的方式有问题
> 单独用$tool指令 和bot对话时，bot会回答自己具备计算、搜索方面的能力了

这里看起来没有调用tool, 我这边测试是正常的

**Comment by nagaki09** [comment]
> > ![9dde1008067a0f1a32a8bfd1119b319](https://user-images.githubusercontent.com/31009189/230566034-b3369b1f-7581-49fd-be03-13b251ff16a2.jpg)
> > 还是算不对，不知道是不是我调用的方式有问题
> > 单独用$tool指令 和bot对话时，bot会回答自己具备计算、搜索方面的能力了
> 
> 这里看起来没有调用tool, 我这边测试是正常的

应用也重启了，不太明白究竟要怎么出发已经安装好的tool

**Comment by goldfishh** [comment]
> > > ![9dde1008067a0f1a32a8bfd1119b319](https://user-images.githubusercontent.com/31009189/230566034-b3369b1f-7581-49fd-be03-13b251ff16a2.jpg)
> > > 还是算不对，不知道是不是我调用的方式有问题
> > > 单独用$tool指令 和bot对话时，bot会回答自己具备计算、搜索方面的能力了
> > 
> > 
> > 这里看起来没有调用tool, 我这边测试是正常的
> 
> 应用也重启了，不太明白究竟要怎么出发已经安装好的tool

```text
bot $tool 使用wolfram计算一下54321*123
```

**Comment by goldfishh** [comment]
toolhub 0.5.0 已支持单tool调用，如仍有问题，请重开本issue
