### ISSUE TITLE
天气获取了不返回信息，只告诉我获取成功了。

### ISSUE THREAD

**Issue by xionghaizhi** [goldfishh/chatgpt-tool-hub#40]
### 问题描述
问天气，只告诉我获取成功了。
![image](https://user-images.githubusercontent.com/30396478/234573653-f410d0a0-6338-4a58-8b1d-f85ae5999408.png)

1. 你复现时的config.json，**注意抹去你的api-key**
```json
{
  "tools": [
    "google-search",
    "morning-news",
    "searxng-search"
  ],
  "kwargs": {
    "openai_api_key": "sk-",
    "proxy": "http://127.0.0.1:7890",
    "debug": false,
    "no_default": false,
    "model_name": "gpt-3.5-turbo",
    "google_api_key": "",
    "google_cse_id": "",
    "common_proxy": "http://127.0.0.1:7890",
    "zaobao_api_key": "",
    "request_timeout": 1000,
    "searx_search_host": "http://127.0.0.1:32283"
  }
}
```

2. 你的问题：

```text
 $tools   今天北京天气
```

3. 收到ai的回复：

```text
 根据您的输入，我已经为您获取了北京今天的天气信息。如果您还需要其他帮助，请告诉我。
```

4. debug模式终端打印的日志：

```text

```

### 环境

 - 操作系统类型  (/Linux)：
 - Python版本  ( 执行 `python -V` )：    Python 3.8.0                  
 - pip版本  ( 执行 `pip -V`)：pip 23.0.1

**Comment by ymeimei** [comment]
我只是想获取当前时间，结果他自动进行操作了。。。最后给我返回天气
![1682518577505](https://user-images.githubusercontent.com/68574727/234604567-2948a70f-b7d6-4965-acb6-1d5c959f0694.jpg)

**Comment by taoguoliang** [comment]
+1，跟帖反馈下bing-search的使用问题，感谢！https://github.com/zhayujie/chatgpt-on-wechat/issues/963

**Comment by goldfishh** [comment]
微信端跟terminal端不同，它无法看到tool过程只能收到结果
如果想要把过程都返回需要专门为微信端优化

**Comment by goldfishh** [comment]
> +1，跟帖反馈下bing-search的使用问题，感谢！[zhayujie/chatgpt-on-wechat#963](https://github.com/zhayujie/chatgpt-on-wechat/issues/963)

你用bing-search并没有返回有用信息
meteo是专门查询天气的，你可以直接用它
现在chatgpt有幻觉，会默认它返回的中间内容用户已经搜到
所以chatgpt会默认你看到如下信息：
```text
[INFO][2023-04-26 13:37:43][tool_engine.py:193] - 我从[meteo-weather]中获得了一些信息：
'根据API文档提供的信息，我们可以使用以下API URL来获取北京市今日的天气情况：\n\nhttps://api.open-meteo.com/v1/forecast?latitude=39.9042&longitude=116.4074&hourly=temperature_2m&timezone=Asia/Shanghai&start_date=2023-04-26&end_date=2023-04-26\n\n该API URL中包含了必要的参数，如经纬度、时区和日期等，以确保我们获取到的是北京市今日的天气情况。通过API的响应结果，我们可以看到北京市今日的每个小时的气温情况，其中包括了13:00时刻的气温数据。因此，根据API提供的数据，北京市13:00时刻的气温为18.5°C。'
```
但是由于你之前指定了很奇怪的工具并且返回了无用的信息，所以chatgpt最后询问你
```text
[INFO][2023-04-26 13:38:04][base.py:226] - LLM-OS的内心独白: 推理：用户可能需要获取特定网站的内容，需要进一步确认
思考：请问用户需要获取哪个网站的内容？
反思：如果用户只是需要一般的网站内容，可以使用url-get工具
```
你在这里需要做的事情是怎么和模型更好的沟通。

**Comment by goldfishh** [comment]
手动关闭长期不活跃issue，如有需求请重新打开。
