### ISSUE TITLE
arxiv 工具初始化失败

### ISSUE THREAD

**Issue by Li-Eternally** [goldfishh/chatgpt-tool-hub#42]
![image](https://user-images.githubusercontent.com/128838111/235102058-7da3c074-9ab4-44af-8503-292aa40710ef.png)
![image](https://user-images.githubusercontent.com/128838111/235102399-72841edf-708c-4f67-91f2-9474e2fe700e.png)

**Comment by goldfishh** [comment]
你好，第一张图片的完整报错信息是什么？

**Comment by Li-Eternally** [comment]
> 你好，第一张图片的完整报错信息是什么？

在执行   Python3 terminal_io.py   命令后弹出tool版本，最后报错进行不了接下来的操作，只有这三行日志

**Comment by goldfishh** [comment]
> > 你好，第一张图片的完整报错信息是什么？
> 
> 在执行 Python3 terminal_io.py 命令后弹出tool版本，最后报错进行不了接下来的操作，只有这三行日志

感谢提出这个issue，fix 了
