### ISSUE TITLE
无法安装 chatgpt-tool-hub，输出setuptools>=40.8.0 错误

### ISSUE THREAD

**Issue by CatcherX** [goldfishh/chatgpt-tool-hub#45]
### 问题描述
无法安装依赖。  
执行：
>pip install -i https://pypi.python.org/simple chatgpt-tool-hub --proxy=127.0.0.1:7890

总是输出：  
【 ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)】

实际上已经安装了的：  
> pip list|findstr "setup"
setuptools         67.7.2 （改为40.8.0 后重试上一操作，依然如此）

### 环境
 - 操作系统类型  (Mac/Windows/Linux)：win11 x64
 - Python版本  ( 执行 `python -V` )： 3.8.9                     
 - pip版本  ( 执行 `pip -V`)：23.1.2

**Comment by CatcherX** [comment]
`Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)'))': /simple/setuptools/
      Could not fetch URL https://pypi.org/simple/setuptools/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/setuptools/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)'))) - skipping
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by goldfishh** [comment]
你好，你的网络环境是什么，可以试试：
```base
pip install  --verbose -i https://pypi.python.org/simple --proxy=127.0.0.1:7890 --trusted-host pypi.python.org --trusted-host pypi.org chatgpt-tool-hub==0.4.3
```

或者

```bash
pip install  -U --verbose -i http://mirrors.aliyun.com/pypi/simple/ chatgpt-tool-hub==0.4.3
```

**Comment by CatcherX** [comment]
找到原因了，外部传参的代理，子进程获取不到。重新配置pip的全局代理后正常
