### ISSUE TITLE
多此一举地问一下，LLM-OS返回的结果可以再characterize一道吗（

### ISSUE THREAD

**Issue by Namarimizu** [goldfishh/chatgpt-tool-hub#49]
### 问题描述

0. 你的问题是否在test.py能复现？

1. 你复现时的config.json，**注意抹去你的api-key**
```
/
```

2. 你的问题：

```text
就是让$tool的回复也能role play
```

3. 收到ai的回复：

```text
/
```

4. debug模式终端打印的日志：

```text
/
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python -V` )：                      
 - pip版本  ( 执行 `pip -V`)：

**Comment by goldfishh** [comment]
我没注意到这个issue，其实是可以做到的
