### ISSUE TITLE
使用python脚本执行出现依赖问题

### ISSUE THREAD

**Issue by theLastWinner** [goldfishh/chatgpt-tool-hub#5]
你好，我这边在个人号接入之后，脚本是需要更新相关依赖的，所以当我执行 `bot $tool 执行 "python3 /root/download.py 40735"`会出现错误，提示：`[Terminal] Command 'python3 /root/download.py 40735' returned non-zero exit status 1.`请问这里的python是调用哪里的服务？我直接在控制台执行脚本是可以跑的。

**Comment by cyinan** [comment]
tool启动不了，提示插件不存在或者未启动，安装这个 pip3 install -r requirements-optional.txt，提示以下结果，不知道哪里出问题了，安装不了~~ 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

**Comment by goldfishh** [comment]
> 你好，我这边在个人号接入之后，脚本是需要更新相关依赖的，所以当我执行 `bot $tool 执行 "python3 /root/download.py 40735"`会出现错误，提示：`[Terminal] Command 'python3 /root/download.py 40735' returned non-zero exit status 1.`请问这里的python是调用哪里的服务？我直接在控制台执行脚本是可以跑的。

你好，Terminal调用你本地的终端执行命令。这个问题我在复现中，会在下个包里修复它。

**Comment by goldfishh** [comment]
> tool启动不了，提示插件不存在或者未启动，安装这个 pip3 install -r requirements-optional.txt，提示以下结果，不知道哪里出问题了，安装不了~~ Traceback (most recent call last): File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook from apport.fileutils import likely_packaged, get_recent_crashes File "/usr/lib/python3/dist-packages/apport/**init**.py", line 5, in from apport.report import Report File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in import apport.fileutils File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket File "/usr/lib/python3/dist-packages/requests_unixsocket/**init**.py", line 1, in import requests File "", line 991, in _find_and_load File "", line 975, in _find_and_load_unlocked File "", line 655, in _load_unlocked File "", line 618, in _load_backward_compatible File "", line 259, in load_module File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/**init**.py", line 95, in File "", line 991, in _find_and_load File "", line 975, in _find_and_load_unlocked File "", line 655, in _load_unlocked File "", line 618, in _load_backward_compatible File "", line 259, in load_module File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in File "/usr/lib/python3/dist-packages/OpenSSL/**init**.py", line 8, in from OpenSSL import crypto, SSL File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in class X509StoreFlags(object): File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

你好，这似乎是你本地依赖环境的问题，你可以试一试

**Comment by theLastWinner** [comment]
> > 你好，我这边在个人号接入之后，脚本是需要更新相关依赖的，所以当我执行 `bot $tool 执行 "python3 /root/download.py 40735"`会出现错误，提示：`[Terminal] Command 'python3 /root/download.py 40735' returned non-zero exit status 1.`请问这里的python是调用哪里的服务？我直接在控制台执行脚本是可以跑的。
> 
> 你好，Terminal调用你本地的终端执行命令。这个问题我在复现中，会在下个包里修复它。

你好，我更新了最新的版本chatgpt_tool_hub-0.3.7，还是存在相同的问题。我要查看当前python版本，提示没有该命令。日志如下；
`
[INFO][2023-04-10 09:32:41][SubscribeAccount.py:31] - [wechatmp] : bot $tool python版本
[INFO][2023-04-10 09:32:52][base.py:99] - 执行Tool: Python REPL中...
[INFO][2023-04-10 09:32:52][bot.py:87] - 行动输入: python --version
[ERROR][2023-04-10 09:32:52][python_repl.py:34] - [python] NameError("name 'python' is not defined")
[INFO][2023-04-10 09:32:59][bot.py:87] - 行动输入: 您需要查看当前系统中安装的Python版本，可以在终端中执行 "python --version" 命令来查看。`

**Comment by goldfishh** [comment]
> > > 你好，我这边在个人号接入之后，脚本是需要更新相关依赖的，所以当我执行 `bot $tool 执行 "python3 /root/download.py 40735"`会出现错误，提示：`[Terminal] Command 'python3 /root/download.py 40735' returned non-zero exit status 1.`请问这里的python是调用哪里的服务？我直接在控制台执行脚本是可以跑的。
> > 
> > 
> > 你好，Terminal调用你本地的终端执行命令。这个问题我在复现中，会在下个包里修复它。
> 
> 你好，我更新了最新的版本chatgpt_tool_hub-0.3.7，还是存在相同的问题。我要查看当前python版本，提示没有该命令。日志如下；
> 
> ```
> [INFO][2023-04-10 09:32:41][SubscribeAccount.py:31] - [wechatmp] : bot $tool python版本
> [INFO][2023-04-10 09:32:52][base.py:99] - 执行Tool: Python REPL中...
> [INFO][2023-04-10 09:32:52][bot.py:87] - 行动输入: python --version
> [ERROR][2023-04-10 09:32:52][python_repl.py:34] - [python] NameError("name 'python' is not defined")
> [INFO][2023-04-10 09:32:59][bot.py:87] - 行动输入: 您需要查看当前系统中安装的Python版本，可以在终端中执行 "python --version" 命令来查看。
> ```
> 
> @goldfishh

你好，bot $tool 使用terminal, 查看python版本

**Comment by theLastWinner** [comment]
> > > > 你好，我这边在个人号接入之后，脚本是需要更新相关依赖的，所以当我执行 `bot $tool 执行 "python3 /root/download.py 40735"`会出现错误，提示：`[Terminal] Command 'python3 /root/download.py 40735' returned non-zero exit status 1.`请问这里的python是调用哪里的服务？我直接在控制台执行脚本是可以跑的。
> > > 
> > > 
> > > 你好，Terminal调用你本地的终端执行命令。这个问题我在复现中，会在下个包里修复它。
> > 
> > 
> > 你好，我更新了最新的版本chatgpt_tool_hub-0.3.7，还是存在相同的问题。我要查看当前python版本，提示没有该命令。日志如下；
> > ```
> > [INFO][2023-04-10 09:32:41][SubscribeAccount.py:31] - [wechatmp] : bot $tool python版本
> > [INFO][2023-04-10 09:32:52][base.py:99] - 执行Tool: Python REPL中...
> > [INFO][2023-04-10 09:32:52][bot.py:87] - 行动输入: python --version
> > [ERROR][2023-04-10 09:32:52][python_repl.py:34] - [python] NameError("name 'python' is not defined")
> > [INFO][2023-04-10 09:32:59][bot.py:87] - 行动输入: 您需要查看当前系统中安装的Python版本，可以在终端中执行 "python --version" 命令来查看。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @goldfishh
> 
> 你好，bot $tool 使用terminal, 查看python版本

@goldfishh 前面加上“ 使用terminal,”命令可以正常执行。但是脚本运行可能会超过20秒，导致中途就会干掉了。是否可以异步执行，然后等程序执行完毕，再回调通知？或者直接异步执行？

**Comment by theLastWinner** [comment]
> > > > > > 你好，我这边在个人号接入之后，脚本是需要更新相关依赖的，所以当我执行 `bot $tool 执行 "python3 /root/download.py 40735"`会出现错误，提示：`[Terminal] Command 'python3 /root/download.py 40735' returned non-zero exit status 1.`请问这里的python是调用哪里的服务？我直接在控制台执行脚本是可以跑的。
> > > > > 
> > > > > 
> > > > > 你好，Terminal调用你本地的终端执行命令。这个问题我在复现中，会在下个包里修复它。
> > > > 
> > > > 
> > > > 你好，我更新了最新的版本chatgpt_tool_hub-0.3.7，还是存在相同的问题。我要查看当前python版本，提示没有该命令。日志如下；
> > > > ```
> > > > [INFO][2023-04-10 09:32:41][SubscribeAccount.py:31] - [wechatmp] : bot $tool python版本
> > > > [INFO][2023-04-10 09:32:52][base.py:99] - 执行Tool: Python REPL中...
> > > > [INFO][2023-04-10 09:32:52][bot.py:87] - 行动输入: python --version
> > > > [ERROR][2023-04-10 09:32:52][python_repl.py:34] - [python] NameError("name 'python' is not defined")
> > > > [INFO][2023-04-10 09:32:59][bot.py:87] - 行动输入: 您需要查看当前系统中安装的Python版本，可以在终端中执行 "python --version" 命令来查看。
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > @goldfishh
> > > 
> > > 
> > > 你好，bot $tool 使用terminal, 查看python版本
> > 
> > 
> > @goldfishh 前面加上“ 使用terminal,”命令可以正常执行。但是脚本运行可能会超过20秒，导致中途就会干掉了。是否可以异步执行，然后等程序执行完毕，再回调通知？或者直接异步执行？
> 
> 你好，建议用prompt 实现这个需求

@goldfishh 好的，谢谢。
