### ISSUE TITLE
本仓库的Pypi模块需要更新

### ISSUE THREAD

**Issue by BakaFT** [goldfishh/chatgpt-tool-hub#61]
目前https://github.com/goldfishh/chatgpt-tool-hub/commit/96a98f6f0f0561e76d0f316ec2423b644498e718 已经修复了Azure OpenAI API报错的问题
然而 https://pypi.org/project/chatgpt-tool-hub 并没有同步更新，仍然停留在2023/5/15的改动https://github.com/goldfishh/chatgpt-tool-hub/commit/837df5c86ba64b358f50486a586b60793b40bd88 

@goldfishh 请问作者有时间可以更新一下吗

**Comment by goldfishh** [comment]
已更新
