### ISSUE TITLE
使用bing-search时报错

### ISSUE THREAD

**Issue by MicroOpeMaster** [goldfishh/chatgpt-tool-hub#8]
[INFO][2023-04-10 11:08:29][base.py:99] - 执行Tool: requests_get中...
[INFO][2023-04-10 11:08:29][bot.py:87] - 行动输入: https://cn.bing.com/search?q=大连市明天天气

[ERROR][2023-04-10 11:08:30][get.py:23] - [requests_get] Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
[INFO][2023-04-10 11:08:32][bot.py:87] - 行动输入: None
[INFO][2023-04-10 11:08:35][wechat_channel.py:164] - [WX] sendMsg=Reply(type=TEXT, content=the response to the original input question in chineseThought: Do I need to use a tool? Yes
Action: requests_get
Action Input: https://cn.bing.com/search?q=大连市明天天气), receiver=@be7690216d93f53e4f0911cf496de7291daee41b5ad11111e6557bd24f01d8a0

我的config.json.template:
{
  "tools": ["python", "requests", "terminal", "meteo-weather", "bing-search"],
  "kwargs": {
      "top_k_results": 2,
      "no_default": false,
      "model_name": "gpt-3.5-turbo",
      "bing_subscription_key": "0db7b530e38b40a5a6b65a94dd79e9"
  }
}

**Comment by goldfishh** [comment]
lxml库没有装上？重新装一下
btw 你的key暴露了

**Comment by nagaki09** [comment]
我向bing请求的时候返回401报错，说我的key无效，可是我就是在微软后台申请的bing-search v7的key。

wolfram倒是跑通了

**Comment by MicroOpeMaster** [comment]
我解决了，一开始我也提示key无效，cp config.json然后又重启了一下不知道怎么就好了，但是问问题的时候总是回复_the response to the original input question in chineseThought: Do I need to use a tool? Yes_，需要问很多次才能成功回答，另外我的meteo-weather还是key无效，这是需要另外注册的吗。最后，我在问题中粘贴的key并不完整

**Comment by goldfishh** [comment]
共性问题：https://github.com/goldfishh/chatgpt-tool-hub/issues/9#issue-1660325995

**Comment by MicroOpeMaster** [comment]
> 你的不同tool，key是放在一个配置段落里面的么？

是的

**Comment by goldfishh** [comment]
这个问题是我的疏忽，有个lxml依赖没有考虑到，已经加在0.4.2了.

**Comment by isanwenyu** [comment]
@goldfishh 请问tool要怎么升级到0.4.2版本？使用#plist查看还是老版本：tool_v0.4 0 - 已启用。
