### ISSUE TITLE
使用chatgpt-on-wechat时，config.json有两个位置，应该哪一份才是对的？

### ISSUE THREAD

**Issue by sky602816027** [goldfishh/chatgpt-tool-hub#80]
### 问题描述

0. 你的问题是否在test.py能复现？

1. 你复现时的config.json，**注意抹去你的api-key**
```json
{
  "tools": [],
  "kwargs": {
      "debug": true  // debug模式一定要打开
  }
}
```

2. 你的问题：

```text
两个位置，一个是/plugins/config.json.template，还有一个位置是在/plugins/tool/config.json.template修改名称保存为一份config.json应该在哪里做？
```

3. 收到ai的回复：

```text
[替换我]
```

4. debug模式终端打印的日志：

```text
[替换我]
```

### 环境

 - 操作系统类型  (Mac/Windows/Linux)：
 - Python版本  ( 执行 `python -V` )：                      
 - pip版本  ( 执行 `pip -V`)：

**Comment by sakura-lj** [comment]
请问最后答案是什么
