### ISSUE TITLE
bdunit 使用问题

### ISSUE THREAD

**Issue by hunli12312** [goldfishh/chatgpt-tool-hub#85]
### 问题描述

0. 你的问题是否在test.py能复现？
无法唤醒bdunit

1. 你复现时的config.json，**注意抹去你的api-key**
```json
{
  "tools": [],
  "kwargs": {
      "debug": true  // debug模式一定要打开
  }
}
```

2. 你的问题：
bdunit 使用问题。
语言模型爱好者非科班出身。bdunit配置完也加载成功之后不知道如何调用，如何唤醒。
希望有大佬可以指路。

3. 收到ai的回复：
[INFO][2023-12-25 11:04:58][wechat_channel.py:194] - [WX] sendMsg=Reply(type=INFO, content=[INFO]
本插件会处理询问实时日期时间，天气，数学运算等问题，这些技能由您的百度智能对话UNIT决定

### 环境

windows python

**Comment by goldfishh** [comment]
试一试tool
实时日期时间可以用terminal、python
天气可以用meteo
数学运算可以用wolfram-alpha
